version: '2'
services:

  bitcoind-api-fe:
    image: bitcoind-api-fe:latest
    build:
      context: .
      dockerfile: $PWD/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - bitcoind
    volumes:
      - .:/usr/src/app
    command: yarn start

networks:
  bitcoind:
    external: true
