export const CUSTOMER_LIST_LOAD_REQUEST = 'CUSTOMER_LIST_LOAD_REQUEST';
export const CUSTOMER_LIST_LOAD_SUCCESS = 'CUSTOMER_LIST_LOAD_SUCCESS';
export const CUSTOMER_LIST_LOAD_ERROR = 'CUSTOMER_LIST_LOAD_ERROR';
